CREATE SCHEMA IF NOT EXISTS ejercicio_modificacion;
USE ejercicio_modificacion;
CREATE TABLE IF NOT EXISTS tabla_1 (a INTEGER, b CHAR(10));
ALTER TABLE tabla_1;
RENAME TABLE tabla_1 TO tabla_2;
ALTER TABLE tabla_2
MODIFY COLUMN a TINYINT NOT NULL;
ALTER TABLE tabla_2
MODIFY COLUMN b CHAR (20);
ALTER TABLE tabla_2
RENAME COLUMN b TO c;
ALTER TABLE tabla_2
ADD COLUMN d TIMESTAMP;
ALTER TABLE tabla_2
DROP COLUMN c;
CREATE TABLE tabla_3 (SELECT * FROM tabla_2);
DROP TABLE IF EXISTS tabla_2;
ALTER TABLE tabla_3;
RENAME TABLE tabla_3 TO tabla_1;
